version: 1.0.{build}
configuration: Release
platform: x64
before_build:
- cmd: git submodule update --init --recursive
- cmd: build-dependencies.cmd
build:
  project: cpp-abci.sln
  parallel: true
  verbosity: minimal
